from .auth import router as auth_router
from .wallets import router as wallets_router
from .categories import router as categories_router
from .transactions import router as transactions_router
from .analytics import router as analytics_router
from .reports import router as reports_router
from .admin import router as admin_router
from .receipts import router as receipts_router
from .logs import router as logs_router
from .users import router as users_router
